version: '3'

services:
  jupyter:
    build: 
      context: .
      args:
        - USER=${LOCAL_USER_NAME}
    image: ${LOCAL_USER_NAME}/jupyter-notebook
    container_name: ${LOCAL_USER_NAME}-jupyter-server
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    volumes:
      - ${HOME}:/home/${LOCAL_USER_NAME}/work
      - ${HOME}/jupyter-notebooks/ssl:/home/${LOCAL_USER_NAME}/ssl
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - LOCAL_USER_ID=${LOCAL_USER_ID:?LOCAL_USER_ID must be set}
      - LOCAL_USER_NAME=${LOCAL_USER_NAME}
    restart: unless-stopped

volumes:
  jupyter-ssl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${JUPYTER_SSL_DIR:-$HOME/jupyter-notebooks/ssl} 