version: '3'

services:
  jupyter:
    build: .
    container_name: jupyter-server
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    volumes:
      - jupyter-notebooks:/home/jupyter/work
      - jupyter-ssl:/home/jupyter/ssl
    restart: unless-stopped
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  jupyter-notebooks:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${JUPYTER_NOTEBOOK_DIR:-$HOME/jupyter-notebooks}
  jupyter-ssl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${JUPYTER_SSL_DIR:-$HOME/jupyter-notebooks/ssl} 