version: '3'

services:
  jupyter:
    build: .
    container_name: jupyter-server
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    volumes:
      - ${JUPYTER_NOTEBOOK_DIR:-${HOME}/jupyter-notebooks}:/home/jovyan/work
      - ${JUPYTER_SSL_DIR:-${HOME}/jupyter-notebooks/ssl}:/home/jovyan/ssl
    restart: unless-stopped
    environment:
      - JUPYTER_ENABLE_LAB=yes
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G 